services:
  db:
    image: pgvector/pgvector:pg16
    container_name: talk_to_pdf_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talk_to_pdf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # This named volume ensures your database data isn't lost if the container stops
  postgres_data: 
